name: talktohumanity
description: A platform designed to say something to humanity
publish_to: "none"
# --------------------------------------------------------------------------------
version: 1.0.0+1
# --------------------------------------------------------------------------------
environment:
  sdk: ">=2.10.5 <3.0.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ------------------------------------
  firebase_core: ^2.4.1
  page_transition: ^2.0.4
  provider: ^6.0.3
#  flutter_native_splash: ^2.2.9
  path_provider: ^2.0.12
  segmented_circle_border: ^2.0.1
  # ------------------------------------
  # Authing
  google_sign_in: ^5.4.4
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  googleapis_auth: ^1.3.1
  firebase_auth: ^4.1.0
  # ------------------------------------
  # Dialogs
  another_flushbar: ^1.10.26
  # ------------------------------------
  # Mediators
  crop_your_image: ^0.7.2
  video_player: ^2.2.10
  youtube_player_flutter: ^8.1.2
  wechat_assets_picker: ^7.3.2
  wechat_camera_picker: ^3.4.0
  image: ^3.0.8
  flutter_svg: ^1.0.3
  youtube_metadata: ^1.0.1
  # ------------------------------------
  # Permitter
  permission_handler: ^10.0.0 # => needed for local contacts_service & sound recorder
  geolocator: ^9.0.1
  # ------------------------------------
  # STORAGE
  firebase_storage: ^11.0.3
  http: ^0.13.4
  # ------------------------------------
  # MY WIDGETS
  widget_fader:
    git:
      url: https://github.com/RagehAz/widget_fader.git
  super_image:
    git:
      url: https://github.com/RagehAz/super_image.git
  super_text:
    git:
      url: https://github.com/RagehAz/super_text.git
  super_box:
    git:
      url: https://github.com/RagehAz/super_box.git
  super_text_field:
    git:
      url: https://github.com/RagehAz/super_text_field.git
  bubbles:
    git:
      url: https://github.com/RagehAz/bubbles.git
  layouts:
    git:
      url: https://github.com/RagehAz/layouts.git
  night_sky:
    git:
      url: https://github.com/RagehAz/night_sky.git
  # ---------------------------
  # MY BACK END PACKAGES
  rest:
    git:
      url: https://github.com/RagehAz/rest.git
  fire:
    git:
      url: https://github.com/RagehAz/fire.git
  ldb:
    git:
      url: https://github.com/RagehAz/ldb.git
  real:
    git:
      url: https://github.com/RagehAz/real.git
  # ------------------------------------
  # MY HELPERS
  bldrs_theme:
    git:
      url: https://github.com/RagehAz/bldrs_theme.git
  scale:
    git:
      url: https://github.com/RagehAz/scale.git
  mapper:
    git:
      url: https://github.com/RagehAz/mapper.git
  numeric:
    git:
      url: https://github.com/RagehAz/numeric.git
  stringer:
    git:
      url: https://github.com/RagehAz/stringer.git
  filers:
    git:
      url: https://github.com/RagehAz/filers.git
  animators:
    git:
      url: https://github.com/RagehAz/animators.git
  space_time:
    git:
      url: https://github.com/RagehAz/space_time.git
  devicer:
    git:
      url: https://github.com/RagehAz/devicer.git
  dialogs:
    git:
      url: https://github.com/RagehAz/dialogs.git
  # ------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  flutter_launcher_icons:
  # ------------------------------------
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/night.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/night.png"
    background_color: "#000000"
    theme_color: "#000000"
  # ------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/videos/
  # ------------------------------------
  fonts:
    - family: BldrsHeadlineFont
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/bldrs_font_bold.ttf

    - family: BldrsBodyFont
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/bldrs_font_regular.ttf

    - family: EnglishHeadline
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: EnglishBody
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/english/Roboto_Thin.ttf
        - asset: packages/bldrs_theme/assets/fonts/english/Roboto_ThinItalic.ttf

    - family: ArabicHeadline
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: ArabicBody
      fonts:
        - asset: packages/bldrs_theme/assets/fonts/arabic/Tajawal_Light.ttf
        - asset: packages/bldrs_theme/assets/fonts/arabic/Tajawal_Regular.ttf
        - asset: packages/bldrs_theme/assets/fonts/arabic/BldrsFont.ttf

    - family: TalkHeadline
      fonts:
        - asset: assets/fonts/tccm.ttf
        - asset: assets/fonts/tccb.ttf
# --------------------------------------------------------------------------------
