// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwtDfKKGjro_5ZAUpHnacKX6ml8ilm3S4',
    appId: '1:569221317127:web:ea39d48602792586ce20a2',
    messagingSenderId: '569221317127',
    projectId: 'talktohumanity',
    authDomain: 'talktohumanity.firebaseapp.com',
    databaseURL: 'https://talktohumanity-default-rtdb.firebaseio.com',
    storageBucket: 'talktohumanity.appspot.com',
    measurementId: 'G-KMR06YL0D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWcBULl0M_V16PvKqSpsilmum42FhHf4',
    appId: '1:569221317127:android:ae98aba66c7dda2ece20a2',
    messagingSenderId: '569221317127',
    projectId: 'talktohumanity',
    databaseURL: 'https://talktohumanity-default-rtdb.firebaseio.com',
    storageBucket: 'talktohumanity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj-FrD92tDfQDbU__0ugHRy7NXOUZVmCw',
    appId: '1:569221317127:ios:d09f9949e7246766ce20a2',
    messagingSenderId: '569221317127',
    projectId: 'talktohumanity',
    databaseURL: 'https://talktohumanity-default-rtdb.firebaseio.com',
    storageBucket: 'talktohumanity.appspot.com',
    androidClientId: '569221317127-71l5dsrpqn9p1tiqbbrllq63g50rf9km.apps.googleusercontent.com',
    iosClientId: '569221317127-apg6rskk26v2mbkccslo2nqughb75h8r.apps.googleusercontent.com',
    iosBundleId: 'com.talktohumanity.talktohumanity',
  );
}
