library dialogs;
// -----------------------------------------------------------------------------
import 'dart:async';
import 'package:another_flushbar/flushbar.dart';
import 'package:bldrs_theme/bldrs_theme.dart';
import 'package:flutter/material.dart';
import 'package:layouts/layouts.dart';
import 'package:scale/scale.dart';
import 'package:stringer/stringer.dart';
import 'package:super_box/super_box.dart';
import 'package:super_text/super_text.dart';
import 'package:talktohumanity/packages/keyboard/keyboard_sensor.dart';
import 'package:talktohumanity/packages/layouts/nav.dart';
import 'package:widget_fader/widget_fader.dart';
// -----------------------------------------------------------------------------
part 'classes/bottom_dialog.dart';
part 'classes/center_dialog.dart';
part 'classes/top_dialog.dart';
// -----------------------------------------------------------------------------
