library dialogs;
// -----------------------------------------------------------------------------
import 'dart:async';
import 'package:another_flushbar/flushbar.dart';
import 'package:bldrs_theme/bldrs_theme.dart';
import 'package:flutter/material.dart';
import 'package:scale/scale.dart';
import 'package:stringer/stringer.dart';
import 'package:super_box/super_box.dart';
import 'package:super_text/super_text.dart';
import 'package:talktohumanity/keyboard_sensor/keyboard_sensor.dart';
import 'package:talktohumanity/services/navigation/nav.dart';
import 'package:talktohumanity/views/widgets/layouts/separator_line.dart';
import 'package:widget_fader/widget_fader.dart';
// -----------------------------------------------------------------------------
part 'dialogs/bottom_dialog.dart';
part 'dialogs/center_dialog.dart';
part 'dialogs/top_dialog.dart';
// -----------------------------------------------------------------------------
